Remove unused optdepends
Otherwise, paru (AUR helper) fails to parse .SRCINFO:

---
$ paru -S gof5
:: Resolving dependencies...
:: Calculating conflicts...
:: Calculating inner conflicts...

Aur (1) gof5-0.1.4-1

:: Proceed to review? [Y/n]: y

:: Downloading PKGBUILDs...
 (1/1) gof5-0.1.4-1                                 [-----------------------------------------------------]
error: failed to parse srcinfo for 'gof5-0.1.4-1': key 'optdepends' requires a value: Line 10: optdepends =
---